version: 0.2

phases:
 install:
   runtime-versions:
     java: corretto17
 build:
   commands:
     - mvn package
 post_build:
   commands:
     ## aws s3 cp target/*.war s3://myhhbucket23 . We don't need this step.
#     - cp target/*.war s3://
     - echo Build completed
artifacts:
  files:
    - build/libs/controller-1.0.0-BUILD-SNAPSHOT.war
#     - index.html
#    - scripts/server_start.sh
#    - scripts/server_stop.sh
    - appspec.yml
    - "dist/**/*"
#  base-directory: build
   
#  discard-paths: yes
