version: 0.2

phases:
 install:
   runtime-versions:
     java: corretto11
 build:
   commands:
     - mvn package
 post_build:
   commands:
     ## aws s3 cp target/*.war s3://myhhbucket23 . We don't need this step.
     - echo Build completed
artifacts:
  files:
    - controller-1.0.0-BUILD-SNAPSHOT.war
#     - index.html
    - scripts/server_start.sh
    - scripts/server_stop.sh
    - appspec.yml
   
  discard-paths: yes
